# Generated by Django 6.0.3 on 2026-03-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuereport',
            old_name='creator',
            new_name='creators',
        ),
    ]
