# Generated by Django 6.0.3 on 2026-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platformadmin', 'PlatformAdmin'), ('creator', 'Creator'), ('subscriber', 'Subscriber'), ('user', 'User')], default='user', max_length=45),
        ),
    ]
