# Generated by Django 6.0.3 on 2026-03-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('subscriptions', '0002_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='subscriptions.product'),
        ),
    ]
